Return event IDs when sending events
inngest/inngest-js pull request #195
Opened 2023-05-13 14:44 UTC by jpwilliams

## Summary

When events are sent to Inngest, return the event IDs from the response.

2023-05-15 13:38 UTC, djfarrelly approved these changes
Hey @jpwilliams - this looks great! The only question that I have on this one is whether we want the return value to be just the event IDs, or is there a possibility in the future to add more data to the response in which case we may want to return an object? e.g.

```ts
const { ids } = await inngest.send([...])
```

I don't currently have any other ideas, but before shipping, I might challenge us to ask the team to think if there are any other ideas in which we might want to pass them through to the client.

2023-05-15 13:38 UTC, djfarrelly commented on src/components/Inngest.ts
> +        .parseAsync(rawBody);
If we decide at some point to return more data from the response and the shape of the response changes, would this parsing fail? Or will it only parse the data expected and ignore the rest?

2023-05-31 16:10 UTC, djfarrelly reviewed
On second review after reviewing the middleware docs @jpwilliams, I'm kind of leaning towards returning the entire response here instead of just the string. We may return other metadata and just returning a string array limits us in the future instead of just returning an object.

2023-06-30 17:52 UTC, djfarrelly requested changes
After further thought - we definitely should return an object for future extensibility. I'll make that change on this branch after rebasing from main.

2023-07-27 11:58 UTC, jpwilliams commented
Closing for #256.

2023-07-27 11:58 UTC, closed without merging