feat: Added h3 server handler to @ingest/h3.
inngest/inngest-js pull request #310
Opened 2023-09-08 15:36 UTC by michealroberts

## Summary

Added h3 server handler to @ingest/h3.

Includes bumping h3 to the latest version (v1.8.1).

## Checklist

- [ ] Added a [docs PR](https://github.com/inngest/website) that references this PR
- [X] Added unit/integration tests
- [X] Added changesets if applicable

2023-09-08 15:50 UTC, michealroberts commented
cc @pi0 Just pinging you here, because usage of the `getRequestURL` utility from h3 fails when used in place of the code in this MR ... it fails on this error:

```
 TypeError: Cannot read properties of undefined (reading 'encrypted')
```

Due to this line here: https://github.com/unjs/h3/blob/12ccb81432a62783fe951a8170976c8162bce44a/src/utils/request.ts#L129

Do you want me to add an issue to https://github.com/unjs/h3 ?

2023-09-08 15:59 UTC, pi0 commented
Hi. Haven’t tried locally but are you somehow mocking request and response objects passed to h3 habdler? 

Regardless feel free to directly open a pr for h3 to make req.connection?. Check optional

2023-09-08 16:12 UTC, michealroberts commented
@pi0 Cool. MR here for you when ready: https://github.com/unjs/h3/pull/532

2023-09-11 21:23 UTC, jpwilliams requested changes
This is great! Thanks for the MR, @michealroberts!

One mini change to some tests and we can get this in. Even has a changeset already! 😍

2023-09-12 09:01 UTC, michealroberts commented on packages/inngest/src/nuxt.test.ts
> +import * as NuxtHandler from "@local/h3";
@jpwilliams Sure! :) Will ammend.

2023-09-13 12:48 UTC, jpwilliams commented
@michealroberts I pushed a quick change to ensure handlers are still reported correctly for the benefit of the UI. It's a touch ugly, but this is changing soon anyway.

Could I grab an example for you for a typical short h3 setup? I'll add an example to the [Serving the Inngest API](https://www.inngest.com/docs/sdk/serve) docs. 🙂

2023-09-13 13:25 UTC, michealroberts commented
> @michealroberts I pushed a quick change to ensure handlers are still reported correctly for the benefit of the UI. It's a touch ugly, but this is changing soon anyway.
> 
> Could I grab an example for you for a typical short h3 setup? I'll add an example to the [Serving the Inngest API](https://www.inngest.com/docs/sdk/serve) docs. 🙂

Cool, yeh I will add an example. It's exactly like Nuxt, but it can be a tad esoteric to know. This would also support nitro as well, which Nuxt is built on.

Kind of like turtles all the way down.

Nuxt 3 > Nitro > h3

2023-09-13 13:51 UTC, jpwilliams commented
@michealroberts Just a quick snippet is fine 🙂 Would something like this be reasonable?

```ts
import { createApp, eventHandler } from "h3";
import { serve } from "inngest/h3";

const app = createApp();

app.use(
  "/api/inngest",
  eventHandler(serve(...)),
);
```

2023-09-13 14:09 UTC, michealroberts commented
@jpwilliams Yaeh, exactly that!

Do you want the same again, but for nitro? https://nitro.unjs.io/

2023-09-19 14:18 UTC, jpwilliams approved these changes

2023-09-19 14:19 UTC, merged